services:
  - type: web
    name: total-admin-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node backend/server.js"
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
